# Generated by Django 4.0.3 on 2022-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='msg',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='hello'),
        ),
    ]
